/*
-- 시퀀스 관리
CREATE SEQUENCE seq_mem_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pet_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_item_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cart_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_cart_item_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_orders_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_orders_item_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_board_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_board_file_idx START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_reply_idx START WITH 1 INCREMENT BY 1;

*/